### ISSUE TITLE
Server console spam about upgrade cache

### ISSUE THREAD

**Issue by juniorjunior** [Nauktis/SolarFlux#19]
Every 30 seconds I get a few (2-4) lines like this:

[08:58:38] [Server thread/FATAL] [SolarFlux/]: Refreshing upgrade cache.

This is after upgrading from 0.5b to 0.6 on a world which had existing solar panels.

Forge Server on Build-1403

**Comment by Nauktis** [comment]
Thanks a lot for taking the time to report the problem. It is a debugging statement I forgot to remove. Nothing to worry about apart from the fact that it will fill up your log. I will upload a new version in a couple of hours.

**Comment by Nauktis** [comment]
Pushed version 0.6a on Curse.
Just for your info, this log statement was not reporting an error. The mod works perfectly fine. It was just the log level that was set to FATAL instead of DEBUG.
