### ISSUE TITLE
Low light upgrade turns solars into magic energy sources

### ISSUE THREAD

**Issue by malianx** [Nauktis/SolarFlux#21]
If you use the low light upgrade solars start producing full power in absolute darkness, even with the top covered by a full block. In fact, if you don't cover the solar it produces less, even during the day time, than one with a block on top.

These aren't solars at that point, they are just magic energy generators that create RF from nothing.

**Comment by Nauktis** [comment]
This is of course not the goal.
I'll have a look into it as soon as possible and will probably change the logic of that particular upgrade.

Thanks for reporting the problem.

**Comment by Nauktis** [comment]
I'll push the fix tonight.
I had to wait as I will release a new feature as well. If it is really urgent for your server, you can always disable the low light upgrade from the config.

**Comment by Nauktis** [comment]
Just pushed version 0.7
I completely changed the way Low Light upgrades influence energy production.
