### ISSUE TITLE
Low light upgrade day/night efficiency

### ISSUE THREAD

**Issue by PhoenixtheII** [Nauktis/SolarFlux#22]
Reproduce:

Have solar panel in view of sky
Put 1 low light upgrade in.

Result

Turns to 40% efficiency @ day
Turns to 50% efficiency @ night

Expected

Turns to 100% efficiency @ day when optimal sun?
Turns to 50% efficiency @ night

**Comment by Nauktis** [comment]
This is an intended behavior.
Low light upgrades allow to generate energy in the dark at the cost of being less efficient when there is too much sun.
Note that I completely changed the way Low Light upgrades influence energy generation in the last version (0.7).
