### ISSUE TITLE
Allow panel size be lower then 0.1

### ISSUE THREAD

**Issue by elix-x** [Nauktis/SolarFlux#28]
Because 1/16=0.0625. And i want them to be very slim. You can push down limit size to 0.0. This will make them 100% flat if choosen...

**Comment by Nauktis** [comment]
I'll remove the limit as soon as I have some time ;)

**Comment by elix-x** [comment]
Thank you!

**Comment by Nauktis** [comment]
Just pushed 0.8b
Sorry it took so long.
