### ISSUE TITLE
No output with no storage

### ISSUE THREAD

**Issue by ghost** [Nauktis/SolarFlux#41]
Preface: I'm trying to make the solar panels from this mod realistic, solar panels irl don't store energy, nor do any from other mods (that I'm aware of).

I believe I've unearthed a bug. If the storage of a panel is set to 0, it will not transfer any power, despite the transfer rate being non-zero and the panel generating power (as shown in its interface). I will admit it's an edge case, but it's still an issue.

**Comment by SerraraFluttershy** [comment]
Sorry to say this, but this mod is abandonware.
The creator hasn't been online since 2016, thus, if you want this fixed...you'll have to fork it yourself.

**Comment by ghost** [comment]
...
github, wtf exactly did you do. I reported this on the solar flux reborn github, somehow it got back here -.-
